function Demo0()
    SetColor(0,1,0)
    SetFlags({monospaced = false})
    local w, h = GetResolution()
    PrintLn("Resolution: "..w.."x"..h)
    PrintLn("ProjectPath: " .. ProjectPath())
    PrintLn("SavePath: " .. GetSavePath())
    PrintLn("CsvPath: " .. GetCsvPath())
    PrintLn("DataPath: " .. DataPath())
    PrintLn("PersistentDataPath: " .. PersistentDataPath())
    PrintLn("IsMobilePlatform: " .. tostring(IsMobilePlatform()))
    PrintLn("Platform: " .. Platform())
    WaitMsgAndClear()
end